module HL.Payroll.Skattetabell.Skattetabell2017

let beregnForskuddstrekk trekkgrunnlag tabellnummer pensjonist tabbtrekkperiode =
    Skattetabell2017internal.beregnForskuddstrekkInternal trekkgrunnlag tabellnummer pensjonist tabbtrekkperiode
