module internal Konstanter

open System

type KonstanterRecord = {
KLASSE1_VANLIG: int
KLASSE2_VANLIG: int
KLASSE1_FINNMARK: int
KLASSE2_FINNMARK:int
TRINN1:int
TRINN2:int
TRINN3:int
TRINN4:int
AVG_FRI_TRYGDEAVGIFT:int
MAX_STFRADRAG:int
MIN_ANV_MINSTE_FRADRAG:int
MAX_ANV_MINSTE_FRADRAG:int
MAX_ANV_MINSTE_FRADRAG_PENSJ:int
MIN_MINSTE_FRADRAG:int
MAX_MINSTE_FRADRAG:int
LONNSFRADRAG:int
ANV_LONNSFRADRAG:int
MAX_SJO_FRADRAG:int

PROSENT_TRINN1:float
PROSENT_TRINN2:float
TRINNSKATT_PROSENT3:float
TRINNSKATT_PROSENT3_FINNMARK:float
PROSENT_TRINN4:float
FELLES_SKATT_VANLIG:float
FELLES_SKATT_FINNMARK:float
SKATTORE:float
TRYGDE_PROSENT:float
LAV_TRYGDEAVG_PROSENT:float
HOY_TRYGDEAVG_PROSENT:float
ANV_MINSTE_FRAD_PROSENT:float
ANV_MINSTE_FRAD_PROSENT_PENSJ:float
MINSTE_FRAD_PROSENT:float
STFRADRAG_PROSENT:float
SJO_PROSENT:float

LAV_GRENSE_TRYGDEAVGIFT:int
HOY_GRENSE_TRYGDEAVGIFT:int

OVERSKYTENDE_PROSENT_VANLIG:int
OVERSKYTENDE_PROSENT_PENSJONIST:int
OVERSKYTENDE_PROSENT_7300_7400:int
OVERSKYTENDE_PROSENT_7350_7450:int
OVERSKYTENDE_PROSENT_7500_7600:int
OVERSKYTENDE_PROSENT_7550_7650:int
OVERSKYTENDE_PROSENT_7700_7800:int
OVERSKYTENDE_PROSENT_0100_0200:int
OVERSKYTENDE_PROSENT_0101_0201:int
OVERSKYTENDE_PROSENT_6300_6400:int
OVERSKYTENDE_PROSENT_6350_6450:int
OVERSKYTENDE_PROSENT_6500_6600:int
OVERSKYTENDE_PROSENT_6550_6650:int
OVERSKYTENDE_PROSENT_6700_6800:int
OVERSKYTENDE_PROSENT_7150_7250:int
OVERSKYTENDE_PROSENT_7160_7260:int
OVERSKYTENDE_PROSENT_7170_7270:int

}

let KonstanterWithTrygdeavgift k =
    {k with
        LAV_GRENSE_TRYGDEAVGIFT = Math.Round ((double k.AVG_FRI_TRYGDEAVGIFT * k.TRYGDE_PROSENT)/(k.TRYGDE_PROSENT - k.LAV_TRYGDEAVG_PROSENT), MidpointRounding.AwayFromZero) |> int;
        HOY_GRENSE_TRYGDEAVGIFT = Math.Round ((double k.AVG_FRI_TRYGDEAVGIFT * k.TRYGDE_PROSENT)/(k.TRYGDE_PROSENT - k.HOY_TRYGDEAVG_PROSENT), MidpointRounding.AwayFromZero) |> int;
    }